name: tabib_line
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  provider: ^6.1.5
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  firebase_auth: ^5.6.2
  easy_localization: ^3.0.7+1
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/static/Comfortaa-SemiBold.ttf
          weight: 600

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
  fonts:
    enabled: true
