// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRDCJk6Y75xklyS9h3fh1KaXbp3S0Cik',
    appId: '1:701272831447:web:30b9aa60f3e0c07d364792',
    messagingSenderId: '701272831447',
    projectId: 'tabibline-c9f93',
    authDomain: 'tabibline-c9f93.firebaseapp.com',
    storageBucket: 'tabibline-c9f93.firebasestorage.app',
    measurementId: 'G-T0YJ8Y915X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqysKkTzDMj6aLGH-vGi-qhL_ENZME7Bg',
    appId: '1:701272831447:android:97450577e86a3cf4364792',
    messagingSenderId: '701272831447',
    projectId: 'tabibline-c9f93',
    storageBucket: 'tabibline-c9f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWsUH1DI6_5or1GNV05eL-M2UpRRoApg',
    appId: '1:701272831447:ios:0abac9c0b95e7d17364792',
    messagingSenderId: '701272831447',
    projectId: 'tabibline-c9f93',
    storageBucket: 'tabibline-c9f93.firebasestorage.app',
    iosBundleId: 'com.example.tabibLine',
  );
}
